### ISSUE TITLE
Formatting of Currency does not follow phones language settings.

### ISSUE THREAD

**Issue by MazyNoc** [monetas/opentxs#40]
Hi. Im Mikael Alfredsson, working on Monets from Simplificator (together with Thomas Ritter).

function : OTAPI_Wrap.FormatAmountWithoutSymbol(assetId, internalAmount);
input: AssetId is referring to an asset in Gold Grams (no decimals allowed)
Problem : When formatting high values, like 5000, the formatter outputs "5,000" even is the device selected language is German ("DE")
The default formatting for Germany should be 'dot' as thousand separator, and 'comma' as decimal.
So in this case, the reader of the text would see 5 grams instead of the requested 5000 grams.

**Comment by mhamrle** [comment]
We have two options:

1. you can do formatting in Java code. To support you we can extend API and provide you everything you need - currency factor see Open-Transactions/opentxs#541, currency symbol and currency TLA.
2. we can modify code to format according to current locale. Could you please confirm that `localeconv` works on Android.

I think that formatting should not be part of opentxs so I vote for 1.

**Comment by MazyNoc** [comment]
I have no problem doing this in Android directly, but what is then the "FormatAmountWithoutSymbol" used for?
Having it all in one place would make sense to get the same behavior on Android and iOS, but as far as I can see, localeconv seems to be useless, but i only seen several years old posts about it.

**Comment by mhamrle** [comment]
`FormatAmountWithoutSymbol` has hardcoded thousand separator and decimal point. It is not suitable for localization. I will prepare PR that provide you all information needed for formatting in Java.
